name: Release

on:
    workflow_dispatch:

jobs:
    ci:
        uses: ./.github/workflows/ci.yml

    release:
        needs: ci
        permissions:
            contents: write
        uses: mcl-playz/actions/.github/workflows/release.yml@main
